
// This file has been generated by the GUI designer. Do not modify.
namespace localfiles
{
	public partial class View
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView list;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Button btAdd;
		private global::Gtk.Button btRemove;
		private global::Gtk.Button btClear;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget localfiles.View
			global::Stetic.BinContainer.Attach (this);
			this.Name = "localfiles.View";
			// Container child localfiles.View.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.list = new global::Gtk.TreeView ();
			this.list.CanFocus = true;
			this.list.Name = "list";
			this.GtkScrolledWindow.Add (this.list);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btAdd = new global::Gtk.Button ();
			this.btAdd.CanFocus = true;
			this.btAdd.Name = "btAdd";
			this.btAdd.UseStock = true;
			this.btAdd.UseUnderline = true;
			this.btAdd.Label = "gtk-add";
			this.vbox3.Add (this.btAdd);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btAdd]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btRemove = new global::Gtk.Button ();
			this.btRemove.CanFocus = true;
			this.btRemove.Name = "btRemove";
			this.btRemove.UseStock = true;
			this.btRemove.UseUnderline = true;
			this.btRemove.Label = "gtk-remove";
			this.vbox3.Add (this.btRemove);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btRemove]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btClear = new global::Gtk.Button ();
			this.btClear.CanFocus = true;
			this.btClear.Name = "btClear";
			this.btClear.UseStock = true;
			this.btClear.UseUnderline = true;
			this.btClear.Label = "gtk-clear";
			this.vbox3.Add (this.btClear);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btClear]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btAdd.Clicked += new global::System.EventHandler (this.onAddClicked);
			this.btRemove.Clicked += new global::System.EventHandler (this.OnRemoveClicked);
			this.btClear.Clicked += new global::System.EventHandler (this.onClearClicked);
		}
	}
}
