
// This file has been generated by the GUI designer. Do not modify.
namespace matewallpaper
{
	public partial class ConfigPage
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.CheckButton cbAutostart;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label3;
		private global::Gtk.SpinButton sbDelay;
		private global::Gtk.ComboBox sbDelayMulti;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label4;
		private global::Gtk.ComboBox cbMode;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button3;
		private global::Gtk.Label label1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView plugins;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget matewallpaper.ConfigPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "matewallpaper.ConfigPage";
			// Container child matewallpaper.ConfigPage.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cbAutostart = new global::Gtk.CheckButton ();
			this.cbAutostart.CanFocus = true;
			this.cbAutostart.Name = "cbAutostart";
			this.cbAutostart.Label = global::Mono.Unix.Catalog.GetString ("Ativar ao iniciar");
			this.cbAutostart.DrawIndicator = true;
			this.cbAutostart.UseUnderline = true;
			this.hbox1.Add (this.cbAutostart);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbAutostart]));
			w1.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Tempo de espera:");
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.sbDelay = new global::Gtk.SpinButton (0, 100, 1);
			this.sbDelay.CanFocus = true;
			this.sbDelay.Name = "sbDelay";
			this.sbDelay.Adjustment.PageIncrement = 10;
			this.sbDelay.ClimbRate = 1;
			this.sbDelay.Numeric = true;
			this.sbDelay.Value = 5;
			this.hbox2.Add (this.sbDelay);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.sbDelay]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.sbDelayMulti = global::Gtk.ComboBox.NewText ();
			this.sbDelayMulti.AppendText (global::Mono.Unix.Catalog.GetString ("Hora(s)"));
			this.sbDelayMulti.AppendText (global::Mono.Unix.Catalog.GetString ("Minuto(s)"));
			this.sbDelayMulti.AppendText (global::Mono.Unix.Catalog.GetString ("Segundo(s)"));
			this.sbDelayMulti.Name = "sbDelayMulti";
			this.sbDelayMulti.Active = 0;
			this.hbox2.Add (this.sbDelayMulti);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.sbDelayMulti]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Modo:");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cbMode = global::Gtk.ComboBox.NewText ();
			this.cbMode.AppendText (global::Mono.Unix.Catalog.GetString ("Linear"));
			this.cbMode.AppendText (global::Mono.Unix.Catalog.GetString ("Aleatório"));
			this.cbMode.Name = "cbMode";
			this.cbMode.Active = 0;
			this.hbox4.Add (this.cbMode);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.cbMode]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseStock = true;
			this.button3.UseUnderline = true;
			this.button3.Label = "gtk-save";
			this.hbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button3]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.notebook1.Add (this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Geral");
			this.notebook1.SetTabLabel (this.vbox1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.plugins = new global::Gtk.TreeView ();
			this.plugins.CanFocus = true;
			this.plugins.Name = "plugins";
			this.GtkScrolledWindow.Add (this.plugins);
			this.notebook1.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow]));
			w14.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Plugins");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow, this.label2);
			this.label2.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button3.Clicked += new global::System.EventHandler (this.OnSaveClicked);
		}
	}
}
